### ISSUE TITLE
Performance of "buffered" bitmaps is 10x worse

### ISSUE THREAD

**Issue by lemire** [lemire/javaewah#51]
We can expect a small performance difference between bitmaps that are backed by an array, and bitmaps that are backed by a java.nio.ByteBuffer instance. However, the current performance difference is huge and probably unacceptable.

I suspect that much of the blame can be put on the getWords method which essentially copies the entier content to an array:

https://github.com/lemire/javaewah/blob/master/src/main/java/com/googlecode/javaewah/LongBufferWrapper.java#L50

Obviously, we would want to avoid such copies if at all possible.

Note that the swap method is similarly sluggish:

https://github.com/lemire/javaewah/blob/master/src/main/java/com/googlecode/javaewah/LongBufferWrapper.java#L151

though it probably does not matter as much.

Here are my results:

            PerformanceTest.cardinality: [measured 3 out of 6 rounds, threads: 1 (sequential)]
             round: 0.49 [+- 0.01], round.block: 0.00 [+- 0.00], round.gc: 0.00 [+- 0.00], GC.calls: 0, GC.time: 0.00, time.total: 3.41, time.warmup: 1.94, time.bench: 1.47
            PerformanceTest.toarray: [measured 3 out of 6 rounds, threads: 1 (sequential)]
             round: 1.52 [+- 0.05], round.block: 0.00 [+- 0.00], round.gc: 0.00 [+- 0.00], GC.calls: 12, GC.time: 0.01, time.total: 9.15, time.warmup: 4.61, time.bench: 4.55
            PerformanceTest.bigunion: [measured 3 out of 6 rounds, threads: 1 (sequential)]
             round: 0.57 [+- 0.01], round.block: 0.00 [+- 0.00], round.gc: 0.00 [+- 0.00], GC.calls: 5, GC.time: 0.00, time.total: 3.52, time.warmup: 1.80, time.bench: 1.72
            PerformanceTest.bigunionbuf: [measured 3 out of 6 rounds, threads: 1 (sequential)]
             round: 2.85 [+- 0.06], round.block: 0.00 [+- 0.00], round.gc: 0.00 [+- 0.00], GC.calls: 16, GC.time: 0.01, time.total: 17.34, time.warmup: 8.78, time.bench: 8.56
            PerformanceTest.toarraybuf: [measured 3 out of 6 rounds, threads: 1 (sequential)]
             round: 11.80 [+- 0.04], round.block: 0.00 [+- 0.00], round.gc: 0.00 [+- 0.00], GC.calls: 118, GC.time: 0.07, time.total: 69.53, time.warmup: 34.14, time.bench: 35.39
            PerformanceTest.cardinalitybuf: [measured 3 out of 6 rounds, threads: 1 (sequential)]
             round: 5.05 [+- 1.15], round.block: 0.00 [+- 0.00], round.gc: 0.00 [+- 0.00], GC.calls: 1, GC.time: 0.00, time.total: 28.06, time.warmup: 12.91, time.bench: 15.15

**Comment by gssiyankai** [comment]
Unfortunately, the getWords method is not called in the benchmarks computing the bitmap cardinality and converting the bitmap to an array. So it cannot explain the poor performance.
Still, I just removed this method.

**Comment by gssiyankai** [comment]
I've noticed a performance difference when I change the backend buffer from a bytebuffer to a longbuffer. Just replace the method convertToMappedBitmap with :
```java
public static EWAHCompressedBitmap convertToMappedBitmap(EWAHCompressedBitmap orig) throws IOException {
        final EWAHCompressedBitmap bitmap = new EWAHCompressedBitmap(LongBuffer.wrap(new long[orig.sizeInBytes()]));
        for (int pos : orig) {
            bitmap.set(pos);
        }
        return bitmap;
    }
```
Here are the results I get (with openjdk/jdk1.8.0_40):
```
PerformanceTest.bigunion: [measured 10 out of 13 rounds, threads: 1 (sequential)]
 round: 0.54 [+- 0.04], round.block: 0.00 [+- 0.00], round.gc: 0.00 [+- 0.00], GC.calls: 1, GC.time: 0.09, time.total: 7.24, time.warmup: 1.89, time.bench: 5.36
PerformanceTest.bigunionbuf: [measured 10 out of 13 rounds, threads: 1 (sequential)]
 round: 1.14 [+- 0.08], round.block: 0.00 [+- 0.00], round.gc: 0.00 [+- 0.00], GC.calls: 2, GC.time: 0.04, time.total: 14.86, time.warmup: 3.47, time.bench: 11.39
PerformanceTest.toarray: [measured 10 out of 13 rounds, threads: 1 (sequential)]
 round: 1.90 [+- 0.03], round.block: 0.00 [+- 0.00], round.gc: 0.00 [+- 0.00], GC.calls: 10, GC.time: 0.02, time.total: 24.96, time.warmup: 5.96, time.bench: 19.00
PerformanceTest.toarraybuf: [measured 10 out of 13 rounds, threads: 1 (sequential)]
 round: 3.36 [+- 0.03], round.block: 0.00 [+- 0.00], round.gc: 0.00 [+- 0.00], GC.calls: 8, GC.time: 0.02, time.total: 43.77, time.warmup: 10.12, time.bench: 33.65
PerformanceTest.cardinalitybuf: [measured 10 out of 13 rounds, threads: 1 (sequential)]
 round: 1.40 [+- 0.01], round.block: 0.00 [+- 0.00], round.gc: 0.00 [+- 0.00], GC.calls: 0, GC.time: 0.00, time.total: 18.25, time.warmup: 4.24, time.bench: 14.00
PerformanceTest.cardinality: [measured 10 out of 13 rounds, threads: 1 (sequential)]
 round: 0.91 [+- 0.03], round.block: 0.00 [+- 0.00], round.gc: 0.00 [+- 0.00], GC.calls: 0, GC.time: 0.00, time.total: 11.84, time.warmup: 2.70, time.bench: 9.14
```
As you can see, the overhead factor here is ~2. So there is a cost to work over a bytebuffer wrapped by a longbuffer.
To explain this 2x factor, I believe it is due to additional bounds checking done by implementations of LongBuffer like HeapLongBuffer when you access a word at a given position.

**Comment by lemire** [comment]
@gssiyankai 

In practice, when doing memory-file mapping, we are going to work from a ByteBuffer. It is how the Java API works.

Cheers!

**Comment by lemire** [comment]
We should change the benchmark so that the mapped bitmaps are actually on disk... this would give us the most realistic test possible.

**Comment by gssiyankai** [comment]
@lemire 

Benchmarks updated.
Results are better, but the 2x factor remains...

Best !

**Comment by lemire** [comment]
@gssiyankai Excellent. We should take some time to study this 2x factor, to make sure it cannot be improved.

**Comment by gssiyankai** [comment]
Do you have an idea of the overhead with roaring bitmap ?

**Comment by lemire** [comment]
It is a valid question. Let me find out.

**Comment by lemire** [comment]
Ok. I have implemented the exact same benchmark with Roaring, see there:

https://github.com/lemire/RoaringBitmap/blob/master/src/test/java/org/roaringbitmap/buffer/TestBenchmarkBasic.java

Assuming that you run the benchmarks on the same machine, the results should be comparable.

Here are the results, on the same machine (recent haswell processor, recent OpenJDK):

        $ java -version
        openjdk version "1.8.0-jdk8u60-b00"
        OpenJDK Runtime Environment (build 1.8.0-jdk8u60-b00-20141223)
        OpenJDK 64-Bit Server VM (build 25.40-b23, mixed mode)

        $ git clone https://github.com/lemire/RoaringBitmap.git
        $ cd RoaringBitmap
        $ mvn -Dtest=TestBenchmarkBasic test
        Running org.roaringbitmap.TestBenchmarkBasic
        TestBenchmarkBasic.bigunion: [measured 10 out of 13 rounds, threads: 1 (sequential)]
         round: 0.47 [+- 0.01], round.block: 0.00 [+- 0.00], round.gc: 0.00 [+- 0.00], GC.calls: 1, GC.time: 0.00, time.total: 6.26, time.warmup: 1.51, time.bench: 4.75
        
        Running org.roaringbitmap.buffer.TestBenchmarkBasic
        TestBenchmarkBasic.bigunionbuf: [measured 10 out of 13 rounds, threads: 1 (sequential)]
         round: 0.92 [+- 0.00], round.block: 0.00 [+- 0.00], round.gc: 0.00 [+- 0.00], GC.calls: 3, GC.time: 0.00, time.total: 12.12, time.warmup: 2.90, time.bench: 9.21
        TestBenchmarkBasic.bigunion: [measured 10 out of 13 rounds, threads: 1 (sequential)]
         round: 0.64 [+- 0.00], round.block: 0.00 [+- 0.00], round.gc: 0.00 [+- 0.00], GC.calls: 2, GC.time: 0.00, time.total: 8.39, time.warmup: 1.98, time.bench: 6.41

         
         
         
        $ git clone https://github.com/lemire/javaewah.git
        $ cd javaewah
        $ mvn -Dtest=PerformanceTest test
        Running com.googlecode.javaewah32.PerformanceTest
        PerformanceTest.bigunion: [measured 3 out of 6 rounds, threads: 1 (sequential)]
         round: 0.44 [+- 0.00], round.block: 0.00 [+- 0.00], round.gc: 0.00 [+- 0.00], GC.calls: 2, GC.time: 0.00, time.total: 2.69, time.warmup: 1.38, time.bench: 1.31
        PerformanceTest.bigunionbuf: [measured 3 out of 6 rounds, threads: 1 (sequential)]
         round: 0.78 [+- 0.00], round.block: 0.00 [+- 0.00], round.gc: 0.00 [+- 0.00], GC.calls: 2, GC.time: 0.00, time.total: 4.73, time.warmup: 2.39, time.bench: 2.34

        Running com.googlecode.javaewah.PerformanceTest
        PerformanceTest.bigunion: [measured 3 out of 6 rounds, threads: 1 (sequential)]
         round: 0.46 [+- 0.00], round.block: 0.00 [+- 0.00], round.gc: 0.00 [+- 0.00], GC.calls: 6, GC.time: 0.00, time.total: 2.81, time.warmup: 1.43, time.bench: 1.38
        PerformanceTest.bigunionbuf: [measured 3 out of 6 rounds, threads: 1 (sequential)]
         round: 0.86 [+- 0.00], round.block: 0.00 [+- 0.00], round.gc: 0.00 [+- 0.00], GC.calls: 7, GC.time: 0.00, time.total: 5.20, time.warmup: 2.63, time.bench: 2.58

**Comment by lemire** [comment]
@gssiyankai 

What these results suggest to me is that our performance is good. That is, we get the same kind of degradation as Roaring.

I would suggest we close this issue and the release JavaEWAH 1.0.0 (yes!). If you have more stuff to get in before this major release, please do so. I have a few irrelevant things to tune out before the release...

**Comment by gssiyankai** [comment]
There's been some discussions about bound checking:
https://groups.google.com/forum/#!topic/mechanical-sympathy/UD0cPwMvNEY
http://stackoverflow.com/questions/11174231/compare-direct-and-non-direct-bytebuffer-get-put-operations
Looks like the best comprise would be to make the LongBufferWrapper work on a long array and update the java.nio.LongBuffer when necessary.

**Comment by gssiyankai** [comment]
@lemire
I have the clear feature that is ready. I've been working on it some weeks ago. I can push it to the project repo by the end of the week.

**Comment by lemire** [comment]
> Looks like the best comprise would be to make the LongBufferWrapper work on a "small" long array and update the java.nio.LongBuffer when necessary

I fail to see how this helps. You might as well deserialize the bitmap, work on it and then re-serialize it as needed. But then you end having to manage your collection of bitmaps in Java RAM: when RAM gets exhausted, you have to release some of the bitmaps, and so on.

The purpose of the memory-file mapping is that you get to avoid this management and let the OS do it for you (and the OS can do it much better in some cases).

**Comment by lemire** [comment]
@gssiyankai 

We might be able to use Unsafe "safely" with this library:

https://github.com/alexkasko/unsafe-tools

Or we could adapt it for our needs.

**Comment by gssiyankai** [comment]
> >  Looks like the best comprise would be to make the LongBufferWrapper work on a "small" long array and update the java.nio.LongBuffer when necessary

> I fail to see how this helps. You might as well deserialize the bitmap, work on it and then re-serialize it as needed. But then you end having to manage your collection of bitmaps in Java RAM: when RAM gets exhausted, you have to release some of the bitmaps, and so on.

> The purpose of the memory-file mapping is that you get to avoid this management and let the OS do it for you (and the OS can do it much better in some cases).

I hope I'll be clearer. What I meant is to use a fixed-size long array, for example a long array of size 10, that will act like a sliding window on the java.nio.LongBuffer. If I know I'm going to read the 10 first words, I can fetch all of them in a one call and copy them in the array at the cost of one bound check instead of 10. But this solution requires more memory (depending on the size of the array) and some changes in all algorithms.

Anyway, forget about this at the moment. As you suggested, let's close the issue and release since javaewah is on par with roaring.

**Comment by lemire** [comment]
@gssiyankai  

Right. The rolling window makes logical sense, but you replace the bound checks with a copy and some other overhead. It is unclear to me whether you will come ahead.

For now, I am closing this particular issue since we agree that the performance is now acceptable.

Eventually, however, we should fight back against this 2x factor.
