### ISSUE TITLE
Some bug about EWAHCompressedBitmap.reverseIntIterator()

### ISSUE THREAD

**Issue by akaala** [lemire/javaewah#53]
Hi, lemire, i'm trying to apply your excellent project javaewah as one of my core component. But i found there seems to be  a bug like following code:

        EWAHCompressedBitmap b = EWAHCompressedBitmap.bitmapOf();
        b.set(1000);
        b.set(100000);
        IntIterator it = b.reverseIntIterator();
        while(it.hasNext())  {
            System.out.println(it.next());
        }

The output is "100000, 99912", not "100000, 1000". I have checked you test cases on reverseIntIterator, where not covered on this kind of case.

Then, i try to use your another project "RoaringBitmap", which could pass this test.

So, could you like to fix this bug, or advise me move onto your new RoaringBitmap?
In my mind, i'd like to move to RoaringBitmap, which seems more powerful and robust.
At last, thank you for your code and time. Your work really helped me a lot!

**Comment by lemire** [comment]
Thanks for the bug report. This has been assigned to @gssiyankai  who should be able to provide a fix in the coming days.

If both javaewah and Roaring could be suitable, I would recommend  you benchmark them and pick whichever works best in your particular application. Depending on what you care about, javaewah could the best choice.

**Comment by lemire** [comment]
Fix will be available in version 1.0.1 which is being released right now.

I am closing this issue, thanks for reporting the problem and thanks to @gssiyankai  for fixing it in a timely manner.
