### ISSUE TITLE
BugReport: clear(int i) would clear ALL map in some particular situation!

### ISSUE THREAD

**Issue by akaala** [lemire/javaewah#54]
I found one serious bug: that in some very specialy situation, one "clear(1535)" action will do like "clear()". Bellowing is my code:

		EWAHCompressedBitmap bm = new EWAHCompressedBitmap();
		for (int i = 1500; i <1600; i ++) {
			bm.set(i);
		}
		for (int i = 1500; i < 1535; i ++) {
			bm.clear(i);
		}
		System.out.println("Before Clean 1535, map is: " +bm);
		bm.clear(1535);
		System.out.println("After Clean 1535, map is: " +bm);

The output will be 

		Before Clean 1535, map is: {1535,1536,1537,1538,1539,1540,1541,1542,1543,1544,1545,1546,1547,1548,1549,1550,1551,1552,1553,1554,1555,1556,1557,1558,1559,1560,1561,1562,1563,1564,1565,1566,1567,1568,1569,1570,1571,1572,1573,1574,1575,1576,1577,1578,1579,1580,1581,1582,1583,1584,1585,1586,1587,1588,1589,1590,1591,1592,1593,1594,1595,1596,1597,1598,1599}
		After Clean 1535, map is: {}

Found this bug both on version 1.0.0 and 1.0.1.
Please fix this. Besides, that really takes a long time to found it...

**Comment by gssiyankai** [comment]
Thanks for reporting the issue. Will provide a fix soon.

**Comment by lemire** [comment]
Fix is being released to maven repository as version 1.0.2. Should be available later today.

Closing.
