### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by ashishgoyal86** [lemire/javaewah#57]
The function insertLiteralWord in EWAHCompressedBitmap32 should have its last two lines in an else block. Otherwise, we get an IndexOutOfBoundsException when the number of literal words are more than RunningLengthWord32.LARGEST_LITERAL_COUNT

**Comment by lemire** [comment]
Acknowledged. Will verify soon.

**Comment by lemire** [comment]
Fixed in release 1.1.1. Thanks for reporting the issue.
