### ISSUE TITLE
ChunkIterator not iterating correctly?

### ISSUE THREAD

**Issue by rhasselbaum** [lemire/javaewah#58]
I am seeing odd behavior in `ChunkIterator`. Either I'm misunderstanding what it does or it's a defect. Here's example code:

```
import com.googlecode.javaewah.*

EWAHCompressedBitmap bitmap = EWAHCompressedBitmap.bitmapOf(52344, 52344 + 9)
ChunkIterator iter = bitmap.chunkIterator()
while(iter.hasNext()) {
    System.out.println(iter.nextBit().toString() + " next length: " + iter.nextLength().toString())
    iter.move(iter.nextLength())
}
```

This produces the output:

```
false next length: 52344
true next length: 1
false next length: 1
true next length: 1
false next length: 7
```

Since there are 8 clear bits between the first and second set bits, I would have expected:

```
false next length: 52344
true next length: 1
false next length: 8
true next length: 1
[...]
```

What's the correct behavior? Thanks.

**Comment by lemire** [comment]
Acknoweldged. Will review soon.

**Comment by gssiyankai** [comment]
@rhasselbaum,
What you are expecting is indeed the correct behavior. I'm working on it.

**Comment by lemire** [comment]
+1 @gssiyankai

**Comment by gssiyankai** [comment]
Fixed.
@lemire, can you issue a new release, please ? Thanks.

**Comment by rhasselbaum** [comment]
Thank you!

**Comment by lemire** [comment]
Part of release 1.1.2.

Closing.

**Comment by lemire** [comment]
+1 @gssiyankai 

Thanks for your report @rhasselbaum
