### ISSUE TITLE
bitmap shift then or

### ISSUE THREAD

**Issue by hoonto** [lemire/javaewah#60]
Wondering if I am doing something wrong here or if this is a bug:

```
import com.googlecode.javaewah.EWAHCompressedBitmap;

public class Test {

    public static void main(String[] args) {
        EWAHCompressedBitmap bm1 = EWAHCompressedBitmap.bitmapOf(10, 11, 12, 13);
        EWAHCompressedBitmap bm2 = bm1.shift(1);
        EWAHCompressedBitmap bm3 = bm1.or(bm2);
        System.out.println("bm1 | bm2: " + bm3);
    }

}
```

results in:

```
Exception in thread "main" java.lang.RuntimeException: You can only reduce the size of the bitmap within the scope of the last word. To extend the bitmap, please call setSizeInBits(int,boolean).
	at com.googlecode.javaewah.EWAHCompressedBitmap.setSizeInBitsWithinLastWord(EWAHCompressedBitmap.java:1409)
	at com.googlecode.javaewah.EWAHCompressedBitmap.orToContainer(EWAHCompressedBitmap.java:1078)
	at com.googlecode.javaewah.EWAHCompressedBitmap.or(EWAHCompressedBitmap.java:1014)
	at Test.main(Test.java:9)
```

Using 1.1.4

Trying to setSizeInBits does not seem to help however.  Note that `bm1.and(bm2)` works fine.

**Comment by lemire** [comment]
Thanks. The ``shift`` function is a recent addition so it might be buggy. I'll have a look.

**Comment by hoonto** [comment]
Thanks so much @lemire , yes I was pleased to see the shift function, it helps in some strange circumstances. For example, one thing I'm trying to do is implement Algorithm 2 on page 10 of http://arxiv.org/pdf/1301.6082.pdf (not using GPU yet, just for fun using JavaEWAH).

**Comment by lemire** [comment]
@hoonto 

I should be able to fix the problem in a few minutes. It is indeed a bug in the ``shift`` function. (It is "easy" to implement new features, harder to produce the needed thorough tests.)

**Comment by lemire** [comment]
Fixed made available through the latest release. The problem was with the ``shift`` function as I suspected. It produced the correct answer, but in a degenerate way that would make the bitmaps fail when they are used in new operations.

**Comment by hoonto** [comment]
ah perfect, thank you @lemire for your incredibly fast response!!
