### ISSUE TITLE
EWAHCompressedBitMap: weird value inside bitmap after set, AND, OR

### ISSUE THREAD

**Issue by svanmald** [lemire/javaewah#74]
Example:

```java
EWAHCompressedBitmap main = new EWAHCompressedBitmap();
EWAHCompressedBitmap other = new EWAHCompressedBitmap();
main = main.or(other);
other.set(7036);
main.set(44002);
other = other.and(main);
other = other.or(main);
System.out.println(other.iterator().next());
```

Output
```
44066
```

**Comment by svanmald** [comment]
Maybe it would be interesting to you to see the framework I made to validate the data structure:

 https://gist.github.com/svanmald/ce73278ba5f9b982050933fc4297de76 

TestEwah::testEwah will automatically look for bugs that take less then 10 steps to reproduce. Once it doesn't find bugs within 10 steps anymore, you can extend it to how many steps you want. Once it found the bug, the framework can print the code to reproduce the issue, given the random seed that was used to generate the issue.

**Comment by lemire** [comment]
Note that all of these bugs you are issuing were created by my bad fix for issue 70.
