### ISSUE TITLE
Support Java Modules

### ISSUE THREAD

**Issue by aalmiray** [lemire/javaewah#83]
`v1.1.3` does not define an explicit module descriptor not an explicit Automatic-Module-Name manifest attribute

```
$ jarviz module name --file JavaEWAH-1.1.13.jar 
subject: JavaEWAH-1.1.13.jar
name: JavaEWAH
source: filename
automatic: true
valid: true

$ jarviz module descriptor --file JavaEWAH-1.1.13.jar 
subject: JavaEWAH-1.1.13.jar
name: JavaEWAH
version: 1.1.13
open: false
automatic: true
requires:
  java.base mandated
contains:
  com.googlecode.javaewah
  com.googlecode.javaewah.datastructure
  com.googlecode.javaewah.symmetric
  com.googlecode.javaewah32
  com.googlecode.javaewah32.symmetric

$ jarviz bytecode show --file JavaEWAH-1.1.13.jar 
subject: JavaEWAH-1.1.13.jar
Unversioned classes. Bytecode version: 52 (Java 8) total: 106
```

I'd be great if the library supplied a full Java module descriptor. It's possible to keep bytecode baseline compatible with Java 8 while providing a full module descriptor thanks to [ModiTect](https://github.com/moditect/moditect). This will help modular projects that consume `JavaEWAH`, specifically those that create custom Java Runtimes with `jlink`, as the latter does not support automatic modules but explicit modules. If interested I can send a PR to make it happen.

**Comment by aalmiray** [comment]
@lemire here we go! 🚀

**Comment by aalmiray** [comment]
Thank you! Be aware that ModiTect `1.0.0.RC3` was just released with a fix for https://github.com/moditect/moditect/issues/179 The bug prevents incremental compilation. I'd recommend upgrading at your earliest convenience.

**Comment by lemire** [comment]
@aalmiray It will be bumped for the next release of javaewah.

**Comment by aalmiray** [comment]
@lemire I can see that release `1.2.3` has been tagged but there are no matching artifacts found in Maven Central so far. Do you need help with publication?

**Comment by lemire** [comment]
@aalmiray This project (javaewah) is still on the legacy [oss.sonatype.org](https://oss.sonatype.org/) which is so slow that it may as well be considered broken. You need to wait at least 24 hours. Sometimes it can take weeks for the artefacts to show up.


I made a video to explain why I considered sonatype to be insufferable:

https://www.youtube.com/watch?v=5EuASOahecA

Please watch it to understand what is going on.

Unfortunately, I think sonatype will not ever upgrade this system. We would need to manually request a move to the new system (https://s01.oss.sonatype.org/) and then update the build accordingly.

**Comment by lemire** [comment]
If the artefacts have not shown up in a week or so, please let me know, I will issue a new release. Sometimes the artefacts just disappear into the ether.

**Comment by aalmiray** [comment]
AFAICT you can request migrating your staging profile to https://s01.oss.sonatype.org/ which takes 10mins or so to make artifacts available after release. It takes 2 or 3hrs for mirrors to be updated.

**Comment by lemire** [comment]
At this point in time, javaewah is a mature library. With some luck, we caught all the bugs. I don't expect anything but a few maintenance releases.

If it were to become active again, I would do as you suggest.

Switching to the new release point is not transparent and requires a fair amount of work.

**Comment by aalmiray** [comment]
Understood. Though when I migrated some of my projects it only took 1 or 2 days for the back office people to handle the switch IIRC.

**Comment by lemire** [comment]
Definitively doable. 

I received an email today, I expect that the artefact have arrived.
